//Variables

@HOST = http://localhost:
@PORT = 8080

@SERVER = {{HOST}}{{PORT}}


### Test the server
{{SERVER}}


### Get all products
GET {{SERVER}}/api/v1/products


### Get product by id
GET {{SERVER}}/api/v1/products/8


### Add a product
POST {{SERVER}}/api/v1/products
Content-Type: application/json

{
  "name": "Acer",
  "description": "An acer laptop that has an intel i7 chip",
  "quantity": 6,
  "price": 19999

}


### Update existing product by id
PUT {{SERVER}}/api/v1/products/2
Content-Type: application/json

{
  "name": "Iphone 15",
  "description": "Pre-owned iphone 15s",
  "quantity": 6,
  "price": 16770
}


### Delete existing product from the database
DELETE {{SERVER}}/api/v1/products/1


//==================== Supplier Server =========================//

### Get all suppliers
GET {{SERVER}}/api/v1/suppliers

### Get supplier by id
GET {{SERVER}}/api/v1/suppliers/2


### Add a supplier
POST {{SERVER}}/api/v1/suppliers
Content-Type: application/json

{
  "email": "teboho@email.com",
  "name": "teboho",
  "phone": "689wed44132"
}

### Update the supplier

PUT {{SERVER}}/api/v1/suppliers/4
Content-Type: application/json

{
  "email": "Tebza@gmail.com",
  "name": "Teboho",
  "phone": "075486458"
}

### Delete the supplier

DELETE {{SERVER}}/api/v1/suppliers/2